### ISSUE TITLE
Please do not fork my repository!

### ISSUE THREAD

**Issue by codeidoscope** [mryap/alembic-kit#1]
Hi,

I received a notification that you had forked my repository. Obviously these are my own notes on my own projects, and will not be useful to you. Please delete [this](https://github.com/mryap/codelogs) repository, and only use the [template repository](https://github.com/codeidoscope/codelogs-template) I created so that you can store your own notes.

Thanks!

**Comment by mryap** [comment]
hi Marion,

As requested, I delete it from my end. https://github.com/mryap/codelogs

Thank you for sharing on dev.to. I always look for ways to put my learning into a central location. Your guide is very handy.

Kind Regards,
Yap

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
